---
- name: Install epel
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - epel-release 
    - yum-utils

- name: Install Repository
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Habilitando repo do PHP 7.0
  command: yum-config-manager --enable remi-php70

- name: Limpando cache do yum
  command: yum clean metadata
  args:
    warn: no

- name: Install PHP 7.0
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - php
    - php-common
    - php-opcache
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysql
    - php-xml
    - php70-php-pear.noarch
    - php70-php-ioncube-loader
    - php70-php-mbstring.x86_64
    - php70-php-pecl-zip
    - php-zipstream.noarch
    - php-pecl-zip.x86_64
    - php70-php-pecl-redis.x86_64
    - php-pecl-redis.x86_64

- name: Configure PHP
  copy:
    src: files/php.ini
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 0755

- name: Configure 20-mbstring.ini
  file:
    src: /etc/opt/remi/php70/php.d/20-mbstring.ini
    dest: /etc/php.d/20-mbstring.ini
    owner: root
    group: root
    state: link

- name: Configure mbstring.so
  file:
    src: /opt/remi/php70/root/usr/lib64/php/modules/mbstring.so
    dest: /usr/lib64/php/modules/mbstring.so
    owner: root
    group: root
    state: link