---
- name: Install Common Packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - wget
    - crontabs

- name: Configure Crontab
  copy:
    src: files/01-alfabetoauto
    dest: /etc/cron.d/01-alfabetoauto
    owner: root
    group: root
    mode: 0755